apiVersion: v1
kind: PersistentVolume
metadata:
  name: evol02
spec:
  storageClassName: evol02sc
  capacity:
    storage: 94Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: "evol02"
    fsType:   "ext4"
