apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: log-volume-placement
spec:
  replicaAffinity:
  - enforcement: required
    matchExpressions:
    - key: media_type
      operator: In
      values:
      - "SSD"
  volumeAntiAffinity:
  - enforcement: required
    matchExpressions:
    - key: type
      operator: In
      values:
      - log
