apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-3D-snapshot
  annotations:
    portworx/app: "mysql"
    portworx/snap-rule: "px-presnap-rules"
spec:
  persistentVolumeClaimName: mysql-data