apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: load-driver
 labels:
   stack: wordpress
   app: load-driver
spec:
 selector:
   matchLabels:
     stack: wordpress
     app: load-driver
 replicas: 1
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       stack: wordpress
       app: load-driver
   spec:
     initContainers:
     - image: appropriate/curl
       name: wait-until-wordpress-up
       args:
       - "sh"
       - "-c"
       - "while ! curl --connect-timeout 2 'wordpress:80' ; do sleep 1 ; done"
     containers:
     - image: centminmod/docker-centos6-siege
       name: siege
       args:
       - "siege"
       - "--benchmark"
       - "--time=24H"
       - "http://wordpress:80"
