##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mysql-data
   labels:
     app: mysql
     stack: wordpress
spec:
   storageClassName: px-mysql-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 8Gi