apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: bXlzcWwxMjM=
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: mysql
    stack: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    stack: wordpress
  clusterIP: None
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: mysql
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: mysql
      stack: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        stack: wordpress
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          tcpSocket:
            port: 3306
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-1
