apiVersion: apis.stork.com/v1alpha1
kind: StorkRule
metadata:
  name: wp-presnap-rule
spec:
  - selector:
      app: mysql
    action:
    - type: command
      background: true
      value: mysql --user=root --password=$MYSQL_ROOT_PASSWORD -Bse  "flush tables with read lock"
  - selector:
      app: wordpress-web
    action:
    - type: command
      runOnAllPods: false
      value: "uname -a" #TBD