apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-web
    stack: wordpress
spec:
  storageClassName: portworx-sc-repl3-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
