apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress-web
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-web
      stack: wordpress
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-web
        stack: wordpress
    spec:
      initContainers:
      - image: alpine:3.7
        name: wait-for-installer
        args:
        - "sh"
        - "-c"
        - "while [ ! -f '/wordpress/installed' ]; do sleep 1; done"
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /wordpress
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 5
        resources:
          requests:
            memory: "2Gi"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress-web
    stack: wordpress
spec:
  ports:
    - port: 80
      name: web
  selector:
    app: wordpress-web
    stack: wordpress
  type: NodePort
