apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: wordpress-3d-snapshot
  annotations:
    portworx.selector/stack: wordpress
    stork.rule/pre-snapshot: px-presnap-rule
spec:
  persistentVolumeClaimName: mysql-pvc-1