apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: wordpress-3d-snapshot
  annotations:
    portworx/stack: wordpress
    portworx/snap-rule: px-presnap-rule
spec:
  persistentVolumeClaimName: mysql-data