apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: volume-db-nodes-or-postgres-affinity
spec:
  rules:
    - replicaAffinity:
        weight: 200
        enforcement: preferred
        labelSelector:
          matchExpressions:
            - key: node_type 
              operator: In
              values:
              - db_hardware
    - volumeAffinity:
        weight: 100
        enforcement: preferred
        labelSelector:
          matchExpressions:
            - key: app
              operator: In      
              values:
              - postgres