apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mongodb-3d-snapshot
  annotations:
    stork.rule/pre-snapshot: px-mongodb-presnap-rule
    stork.rule/post-snapshot: px-mongodb-postsnap-rule
spec:
  persistentVolumeClaimName: px-mongo-pvc
