apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: px-mongodb-postsnap-rule
spec:
  - podSelector:
      app: px-mongo-mongodb
    actions:
    - type: command
      value: mongo --eval "printjson(db.fsyncUnlock())"
