##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: portworx-io-priority-low
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
   snap_interval:   "70"

---

##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: debug-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: portworx-io-priority-low
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi