apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: StoragePolicy
metadata:
  name: volume-upgrade-tier
  namespace: postgres
spec:
  ##### selector allows providing label selectors to filter down the objects that are applicable to this policy 
  selector:
    matchLabels:
      app: postgres
  ##### conditions are the symptoms to evaluate
  conditions:
    - key: openstorage.io.condition.volume/latency_ms
      operator: gt
      values:
        - 15
    - key: openstorage.io.condition.disk/latency_ms
      operator: gt
      values:
        - 30
  ##### actions is the action to perform when all conditions are met
  action:
    name: openstorage.io.action.volume/move