apiVersion: v1
kind: Pod
metadata:
  name: torpedo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  containers:
  - args:
    - --trace
    - --vv
    - --failFast
    - --skip=SetupTeardown|AppTasksDown|VolumeDriverDown|VolumeDriverAppDown|DriveFailure|RebootOneNode|RebootAllNodes|UpgradeVolumeDriver
    - --slowSpecThreshold
    - "600"
    - ""
    - bin/basic.test
    - bin/reboot.test
    - bin/upgrade.test
    - bin/drive_failure.test
    - --
    - --spec-dir
    - ../drivers/scheduler/k8s/specs
    - --app-list
    - wordpress
    - --node-driver
    - ssh
    - --scale-factor
    - "1"
    - ""
    - ""
    command:
    - ginkgo
    env:
    - name: TORPEDO_SSH_USER
    - name: TORPEDO_SSH_PASSWORD
      value: Password1
    image: harshpx/torpedo:latest
    imagePullPolicy: Always
    name: torpedo
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  nodeName: k2m
  restartPolicy: Never
  serviceAccount: torpedo-account
  serviceAccountName: torpedo-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
