##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: pxtestsc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ns.default-name.pxtestsnap
  annotations:
    volume.beta.kubernetes.io/storage-class: pxtestsc
    px/snapshot-source-pvc: nosuchpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi