apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: each-replica-in-different-zone
spec:
  replicaAntiAffinity:
    - enforcement: required
      topologyKey: failure-domain.kubernetes.io/zone
