apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: kafka-stability2-placement-rules
spec:
  rules:
    replicaAffinity:
    - enforcement: required
      topologyKey: failure-domain.kubernetes.io/rack
    volumeAntiAffinity:
    - enforcement: required
      topologyKey: failure-domain.kubernetes.io/rack
      matchExpressions:
        - key: application 
          operator: In
          values:
            - "kafka"
        - key: service
          operator: In        
          values:
            - "stability2"
        - key: environment
          operator: In
          values:
            - "prod"