apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: enclosure-spread
spec:
  rules:
    - affectedReplicas: 1
      enforcement: preferred
      type: affinity
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SSD"
    - affectedReplicas: 1
      enforcement: preferred
      type: affinity
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SSD"
    - enforcement: preferred
      type: affinity
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SATA"
