##### Pod using a volume dynamically provisioned from a volume claim
apiVersion: v1
kind: Pod
metadata:
   name: px-nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: px/running
            operator: NotIn
            values:
            - "false"
          - key: px/enabled
            operator: NotIn
            values:
            - "false"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test-volume
      mountPath: /mnt
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: px-demo-pvc