apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: volume-infra-node-affinity
spec:
  replicaAffinity:
    - enforcement: required
      matchExpressions:
        - key: "node-type"  # Can be any label on the k8s node
          operator: In      # NotIn, Exists, DoesNotExist, Gt, Lt
          values:
          - "infra"
