apiVersion: stork.libopenstorage.org/v1alpha1
kind: GroupVolumeSnapshot
metadata:
  name: fio-group-snapshot-cloud
spec:
  pvcSelector:
    matchLabels:
      name: fio-claim-app
  options:
    portworx/snapshot-type: cloud
