kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-repl-3
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-repl-1
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-claim-1
  labels:
    name: fio-claim-app
spec:
  storageClassName: px-repl-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-claim-2
  labels:
    name: fio-claim-app
spec:
  storageClassName: px-repl-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
