---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: nginx
    tier: app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wordpress
    tier: app
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: app
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: phpfpm
  selector:
    app: wordpress
    tier: app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wordpress
        app: wordpress
        tier: app
    spec:
      containers:
      - image: bswatson/wordpress:php7.1-fpm-0.2
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 9000
          name: phpfpm
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      - image: bswatson/nginx-wordpress:0.27
        name: web
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
