apiVersion: v1
kind: ServiceAccount
metadata:
  name: torpedo-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: torpedo-role
rules:
  -
    apiGroups:
      # have access to everything except Secrets
      - "*"
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: torpedo-role-binding
subjects:
- kind: ServiceAccount
  name: torpedo-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: torpedo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: torpedo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  containers:
  - args:
    - --trace
    - --failFast
    - --slowSpecThreshold
    - "600"
    - --v
    - --focus={SetupTeardown}|{AppTasksDown}|{VolumeDriverCrash}
    - bin/basic.test
    - bin/reboot.test
    - bin/drive_failure.test
    - bin/volume_ops.test
    - --
    - --spec-dir
    - ../drivers/scheduler/k8s/specs
    - --app-list
    -  nginx,postgres,wordpress
    - --node-driver
    - ssh
    - --scale-factor
    - "1"
    command:
    - ginkgo
    env:
    - name: TORPEDO_SSH_USER
      value: root
    - name: TORPEDO_SSH_PASSWORD
      value: Password1
    image: portworx/torpedo:latest
    imagePullPolicy: Always
    name: torpedo
    tty: true
  restartPolicy: Never
  schedulerName: default-scheduler
  serviceAccount: torpedo-account
  serviceAccountName: torpedo-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal