kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: ns.dev-name.pxtestsnap
  annotations:
    volume.beta.kubernetes.io/storage-class: pxtestsc
    px/snapshot-source-pvc: pxtestpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi