##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-sc-groupA
provisioner: kubernetes.io/portworx-volume
parameters:
   group: groupA
   fg: "true"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-groupA-vol1
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-groupA
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-groupA-vol2
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-groupA
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-groupA-vol3
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-groupA
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-pvc-groupA-vol4
   annotations:
     volume.beta.kubernetes.io/storage-class: px-sc-groupA
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
