apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: px-wipe-config
spec:
  selector:
    matchLabels:
      name: px-wipe-config
  template:
    metadata:
      labels:
        name: px-wipe-config
    spec:
      containers:
        - name: px-wipe-config
          image: busybox:latest
          command:
          - "echo "removing /etc/pwx""
          - "rm -rf /etc/pwx/config.json"
          - "while true; do sleep 1; done"
          volumeMounts:
            - name: etcpwx
              mountPath: /etc/pwx
      restartPolicy: Never
      volumes:
        - name: etcpwx
          hostPath:
            path: /etc/pwx