apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: volume-db-nodes-or-postgres-affinity
spec:
  rules:
    - weight: 200
      enforcement: preferred
      affinity:
        matchExpressions:
          - key: node_type 
            operator: In
            values:
            - db_hardware
    - weight: 100
      enforcement: preferred
      affinity:
        matchExpressions:
          - key: app
            operator: In      
            values:
            - postgres
