apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: cassandra-volume-anti-affinity
spec:
  rules:
    - type: antiAffinity
      matchExpressions:
        - key: app 
          operator: In
          values:
          - cassandra