apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: postgres-volume-affinity
spec:
  rules:
    - type: affinity
      matchExpressions:
        - key: app 
          operator: In
          values:
          - postgres