apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: postgres-volume-affinity
spec:
  rules:
    - affinity:
        volumeAffinity:
          enforcement: preferred 
          labelSelector:
            matchExpressions:
            - key: app
              operator: In      
              values:
              - postgres