apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: cassandra-volume-anti-affinity
spec:
  rules:
    - type: antiAffinity
      matchExpressions:
        - key: app 
          operator: In
          values:
          - cassandra