apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: ssd-sata-pool-placement-spread
spec:
  rules:
    # first replica in SSD
    - affinity:
        replicaAffinity:
          affectedReplicas: 1
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SSD"
    # second in SATA
    - affinity:
        replicaAffinity:
          affectedReplicas: 1
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SATA"
