apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: ssd-pool-placement
spec:
  rules:
    - replicaAffinity:
        matchExpressions:
        - key: media_type
          operator: In
          values:
          - "SSD"
