apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: anti-ssd-pool-placement
spec:
  rules:
    - replicaAntiAffinity:
        matchExpressions:
        - key: media_type
          operator: In
          values:
          - "SATA"