# Concept spec on future px operator
apiVersion: px.io/v1alpha1
kind: Cluster
metadata:
  name: px
# namespace: kube-system
spec:
  versionTag: 1.2.5
  management: true        # deploys lighthouse
  storage:                # cluster level storage configuration and selection
    useAllNodes: true
    useAllUnusedDevices: true
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
#   nodes:
#   - name: "minion-1"
#      # no devices to zeroStorage mode
#   - name: "minion-2"
#     devices:             # specific devices to use for storage can be specified for each node
#     - name: "sdb"
#     - name: "sdc"
# etcdSize: 3
