kind: PersistentVolumeClaim
apiVersion: v1
  metadata:
    name: pxtestsnap
    annotations:
      volume.beta.kubernetes.io/storage-class: px-nginx-sc
      px/snapshot-source-namespace: default
      px/snapshot-source-pvc: pxtestpvc
spec:
  resources:
    requests:
      storage: 1Gi