apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
 name: volumeplacementstrategies.portworx.io
spec:
 group: portworx.io
 version: v1beta1
 scope: Cluster
 names:
   plural: volumeplacementstrategies
   singular: volumeplacementstrategy
   kind: VolumePlacementStrategy
   shortNames:
   - vps
   - vp