apiVersion: v1
kind: PersistentVolume
metadata:
  name: data03
  labels:
    type: local
spec:
  storageClassName: data03sc
  capacity:
    storage: 94Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elkvol"
