apiVersion: v1
kind: PersistentVolume
metadata:
  name: data02
  labels:
    type: local
spec:
  storageClassName: data02sc
  capacity:
    storage: 94Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elkvol"
