apiVersion: v1
kind: PersistentVolume
metadata:
  name: evol01
spec:
  storageClassName: evol01sc
  capacity:
    storage: 94Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: "evol01"
    fsType:   "ext4"
