apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: px-mysql-postsnap-rule
spec:
- actions:
  - type: command
    value: mysql --user=root --password=password -Bse 'unlock tables;'
  - type: command
    value: echo "---------------------------------------Finished Snap------------------------------------------------"
  podSelector:
    app: mysql
