##### Portworx storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-pgbench-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  nodes: "f4587f8c-8df0-4cb1-9740-5431da0e8b0a"
allowVolumeExpansion: true
