##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: pxtestsc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pxtestpvc
   annotations:
     volume.beta.kubernetes.io/storage-class: pxtestsc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi