kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # format is name.<new_volume_name>-source.<old_pvc_pxsnap_name>
  name: name.restore001-source.snap001
  annotations:
    volume.beta.kubernetes.io/storage-class: px-demo-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi