kind: PersistentVolumeClaim
apiVersion: v1
  metadata:
    namespac: prod
    name: pxtestsnap-ns.prod
    annotations:
      volume.beta.kubernetes.io/storage-class: pxtestsc
      px/snapshot-source-pvc: pxtestpvc
spec:
  resources:
    requests:
      storage: 1Gi