apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: maria
spec:
  serviceName: "maria"
  replicas: 1
  template:
    metadata:
      labels:
        app: maria
    spec:
      schedulerName: stork
      terminationGracePeriodSeconds: 10
      containers:
      - name: maria
        image: mariadb:10.1
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: test
        ports:
        - containerPort: 3306
          name: maria
        volumeMounts:
        - name: mariadb-data-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data-vol
        portworxVolume:
          volumeID: mariadb-data-vol