apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: inter-volume-placement
spec:
  affinity:
    volumeAffinity:
      - required: true
        labelSelector:
          matchExpressions:
          - key: tier
            operator: In      # NotIn, Exists, DoesNotExist, Gt, Lt
            values:
            - T2
            - T3
    volumeAntiAffinity:
      - required: false
        weight: 100
        labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - T1