apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: default
  annotations:
    portworx.placement: "pool-placement-ssd"
spec:
  persistentVolumeClaimName: mysql-data