apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: cassandr-presnap-rule
spec:
  - podSelector:
      app: cassandra
    actions:
    - type: command
      value: nodetool flush
