apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: default
  annotations:
    libopenstorage/placement: "ssd-pool-placement"
spec:
  persistentVolumeClaimName: mysql-data
