apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: ssd-pool-placement
spec:
  rules:
    - enforcement: required
      affinity:
        matchExpressions:
        - key: media_type
          operator: In
          values:
          - "SSD"
      antiAffinity:
        matchExpressions:
        - key: type
          operator: In
          values:
          - log
