apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: ssd-pool-placement
spec:
  affinity:
    poolAffinity:
      - enforcement: preferred     # Can be "preferred" or "required" (default)
        labelSelector:
          matchExpressions:
          - key: media_type
            operator: In           # NotIn, Exists, DoesNotExist, Gt, Lt
            values:
            - "SSD"