apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: ssd-sata-pool-placement-spread
spec:
  rules:
    - affectedReplicas: 1
      enforcement: required
      type: affinity
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SSD"
    - affectedReplicas: 1
      enforcement: required
      type: affinity 
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SATA"