apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: ssd-sata-pool-spread-placement
spec:
  affinity:
    poolAffinity:
      - replicaPlacementAlgorithm: "spread" # Useful when multiple pools match the selector. Can be spread, binpack, auto, random.
        labelSelector:
          matchExpressions:
          - key: media_type
            operator: In             # NotIn, Exists, DoesNotExist, Gt, Lt
            values:
            - "SSD"
            - "SATA"

##### Optional fields not included above that have default values
      # enforcement: required
      # weight: 100
