apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: ssd-sata-pool-placement-spread
spec:
  rules:
    - affectedReplicas: 1
      affinity:
        poolAffinity:
          enforcement: required
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SSD"
    - affectedReplicas: 1
      affinity:
        poolAffinity:
          enforcement: required
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SATA"