apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: anti-ssd-pool-placement
spec:
  rules:
    - affinity:
        poolAntiAffinity:
          enforcement: required
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SSD"
