apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: ssd-pool-placement
spec:
  rules:
    - affinity:
        poolAffinity:
          enforcement: required
          labelSelector:
            matchExpressions:
            - key: media_type
              operator: In
              values:
              - "SSD"
