apiVersion: portworx.io/v1beta1
kind: VolumePlacementStrategy
metadata:
  name: ssd-pool-placement
spec:
  rules:
    - type: affinity
      matchExpressions:
      - key: media_type
        operator: In
        values:
        - "SSD"
