apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: one-ssd-other-sata-pool-placement
spec:
  rules:
    - affectedReplicas: 1
      enforcement: required
      affinity:
        matchExpressions:
        - key: media_type
          operator: In
          values:
          - "SSD"
    - enforcement: required
      affinity:
        matchExpressions:
        - key: media_type
          operator: In
          values:
          - "SATA"
