apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: us-east-1a-b-zone-affinity
spec:
  rules:
    - affinity:
        nodeAffinity:
          enforcement: required                              # Can be "preferred" or "required" (default)
          labelSelector: 
            matchExpressions:
            - key: "failure-domain.beta.kubernetes.io/zone"  # Can be any label on the k8s node
              operator: In                                   # NotIn, Exists, DoesNotExist, Gt, Lt
              values:
              - "us-east-1a"
              - "us-east-1b"
