apiVersion: libopenstorage.org/v1alpha1
kind: VolumePlacementStrategy
metadata:
  name: rack-1-2-3-affinity
spec:
  rules:
    - affinity:
        matchExpressions:
          - key: "failure-domain.portworx/rack"  # Can be any label on the k8s node
            operator: In                         # NotIn, Exists, DoesNotExist, Gt, Lt
            values:
            - "rack-1"
            - "rack-2"
            - "rack-3"
