##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-nginx-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-nginx-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: pod-stop
    spec:
      containers:
      - name: pod-stop
        image: harshpx/pod-stop:latest
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /var/sighandler
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: px-nginx-pvc
