apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: default
  annotations:
    stork/placement: "ssd-sata-pool-spread-placement"
spec:
  persistentVolumeClaimName: mysql-data