apiVersion: v1
kind: PersistentVolume
metadata:
  name: convergence-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: "convergence-test"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: convergence-test
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
