kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ns.default-name.pxtestrestore
  annotations:
    volume.beta.kubernetes.io/storage-class: pxtestsc
    px/snapshot-source-pvc: ns.default-name.pxtestsnap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi