apiVersion: apps/v1
kind: Deployment
metadata:
  name: poor-mans-docker-reg
spec:
  selector:
    matchLabels:
      app: registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  labels:
    name: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: reg
      protocol: TCP
      port: 5000
      targetPort: 5000